<script setup lang="ts">
import type { SpotifyCodeDTO } from '@/types/spotifyDTO.ts'
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import CopyToClipboardContent from '@/components/CopyToClipboardContent.vue'
import SongTitle from '@/components/SongTitle.vue'
import ColorDisplay from '@/components/ColorDisplay.vue'
import { useClipboard } from '@/composables/useClipboard.ts'
import ApiResultDownloadButton from '@/components/ApiResultDownloadButton.vue'
import ApiResultPrintButton from '@/components/ApiResultPrintButton.vue'
import { useTouchDetector } from '@/composables/useTouchDetector.ts'
import { SpotifyItemType } from '@/types/spotifyType.ts'

const props = defineProps<{
  apiResult: SpotifyCodeDTO
  albumImageUrl: string | null
  requestWhileSaved: boolean
}>()

const emit = defineEmits<{
  (e: 'update:requestWhileSaved', value: boolean): void
}>()

const barResult = computed(() => {
  return props.apiResult.bars
})
const albumColorResult = computed(() => {
  if (!props.apiResult.album_image_color) return null
  return props.apiResult.album_image_color
})

const apiResultRef = ref<HTMLElement | null>(null)
const clipboard = useClipboard()
const touchDetector = useTouchDetector()

const { isTouch } = touchDetector

const isHighlighting = ref(false)

const basePageTitle = 'Print Your Song'

onMounted(() => {
  nextTick(() => {
    apiResultRef.value?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
    })
  })
})

watch(
  () => props.apiResult.title,
  (newTitle) => {
    if (newTitle) {
      document.title = `${basePageTitle} - ${newTitle}`
    } else {
      document.title = basePageTitle
    }
  },
)

watch(
  () => props.requestWhileSaved,
  (newValue) => {
    if (!newValue) return
    nextTick().then(() => {
      apiResultRef.value?.scrollIntoView({
        behavior: 'smooth',
        block: 'nearest',
      })
    })
    isHighlighting.value = true
    setTimeout(() => {
      isHighlighting.value = false
    }, 1200)
    emit('update:requestWhileSaved', false)
  },
)
</script>

<template>
  <div ref="apiResultRef" class="api-result-wrapper" :class="{ pulse: isHighlighting }">
    <div
      v-if="albumImageUrl"
      class="bg"
      :style="{ backgroundImage: `url(${props.albumImageUrl})` }"
    ></div>
    <v-skeleton-loader
      v-else
      class="bg"
      :loading="!props.albumImageUrl"
      type="image"
      style="
        background: linear-gradient(145deg, rgba(239, 226, 140, 0.3), rgba(255, 255, 255, 0.1));
      "
    ></v-skeleton-loader>
    <div class="content">
      <SongTitle key="spot-title" :title="apiResult.title" :type="apiResult.type" />
      <div key="code-parts" class="code-parts">
        <CopyToClipboardContent
          label="Code Part 1"
          :text="barResult.octal_part1 + ''"
          @copy-to-clipboard="clipboard.copy('' + barResult.octal_part1, 'Code Part 1')"
        />
        <CopyToClipboardContent
          label="Code Part 2"
          :text="barResult.octal_part2 + ''"
          @copy-to-clipboard="clipboard.copy('' + barResult.octal_part2, 'Code Part 2')"
        />
      </div>
      <div v-if="albumColorResult" key="color-recommendations" class="color-recommendation">
        <h2 class="filament-title">Color Suggestion</h2>
        <div class="color-box-wrapper">
          <ColorDisplay label="Base" :color="albumColorResult.accent_color" />
          <ColorDisplay label="Code" :color="albumColorResult.code_color" />
        </div>
      </div>
      <div v-else>
        <h2 class="filament-title">No Color Recommendation</h2>
        <p v-if="apiResult.type === SpotifyItemType.Playlist" class="text-grey-darken-1">
          Most likely your playlist does not have a custom <br/> cover image (not auto generated by Spotify).
        </p>
        <p v-else class="text-grey-darken-1">
           Most likely the Spotify Service is not available. <br/> The downloads will most likely also not work.
        </p>
      </div>
      <div class="actions" :class="{ bottom: isTouch }">
        <ApiResultPrintButton
          v-if="albumColorResult || apiResult.type !== SpotifyItemType.Playlist"
          :job-id="apiResult.job_id"
          class="btn print-btn"
          :class="{ bottom: isTouch }"
        />
        <span v-if="isTouch" class="action-help-msg" :class="{ bottom: isTouch }"
          >Album Image Actions</span
        >
        <ApiResultDownloadButton
          v-if="albumColorResult || apiResult.type !== SpotifyItemType.Playlist"
          :job-id="apiResult.job_id"
          class="btn album-btn"
          :class="{ bottom: isTouch }"
        />
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
@use '@/styles/animations';

.api-result-wrapper {
  position: relative;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  border: 3px solid #fdeca4;
  border-radius: 24px;
}
.api-result-wrapper .bg {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-size: cover;
  background-position: center;
  transform: scale(1.1);
  filter: brightness(0.5);
  z-index: 0;
}

.api-result-wrapper .content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  backdrop-filter: blur(8px);
  padding: 8px 16px;
  z-index: 1;
}

//.api-result-wrapper {
//  display: flex;
//  flex-direction: column;
//  align-items: center;
//  gap: 16px;
//  border: 3px solid #fdeca4;
//  padding: 8px 16px;
//  border-radius: 24px;
//  background: linear-gradient(145deg, rgba(239, 226, 140, 0.3), rgba(255, 255, 255, 0.1));
//  backdrop-filter: blur(10px);
//}

.code-parts {
  display: flex;
  flex-direction: row;
  gap: 32px;
}

.filament-title {
  color: #f4d6a2;
}

.color-box-wrapper {
  display: flex;
  flex-direction: row;
  gap: 16px;
  justify-content: center;
  align-items: center;
}

.color-recommendation {
  display: flex;
  flex-direction: column;
  align-items: center;
}

@media (max-width: 600px) {
  .code-parts {
    flex-direction: column;
    align-items: stretch;
  }

  .api-result-wrapper {
    align-items: stretch;
  }

  .color-recommendation {
    align-items: stretch;
  }
  .color-box-wrapper {
    flex-direction: column;
    align-items: stretch;
  }
}

.btn {
  position: absolute;
  top: 4px;

  &.bottom {
    position: static;
    bottom: 4px;
  }
}

.print-btn {
  right: 4px;
}

.album-btn {
  left: 4px;
}

.action-help-msg {
  display: none;

  &.bottom {
    display: inline-block;
    font-size: 0.9em;
    color: #f4d6a2;
    margin-right: 8px;
  }
}

.actions {
  &.bottom {
    display: flex;
    flex-direction: row-reverse;

    width: 100%;
    align-items: center;
    justify-content: space-between;

    border: 1px solid #fdeca4;
    padding: 2px;
    border-radius: 2rem;
  }
}

//.actions .bottom {
//  display: flex;
//  flex-direction: row-reverse;
//
//  width: 100%;
//  align-items: center;
//  justify-content: space-between;
//}
//
//.btn .bottom {
//  position: static;
//  bottom: 4px;
//}

@media (max-width: 600px) {
  .btn {
    position: static;
    bottom: 4px;
  }

  .actions {
    display: flex;
    flex-direction: row-reverse;

    width: 100%;
    align-items: center;
    justify-content: space-between;
  }

  .action-help-msg {
    display: inline-block;
    font-size: 0.9em;
    color: #f4d6a2;
    margin-left: 8px;
  }
}

.pulse {
  animation: scale-pulse 1.2s cubic-bezier(0.34, 1.56, 0.64, 1);
}

//.print-btn {
//  position: absolute;
//  right: 0;
//  top: 0;
//  margin: 4px;
//}
//
//.album-btn {
//  position: absolute;
//  left: 0;
//  top: 0;
//  margin: 4px;
//}
</style>
